In [2]:
import numpy as np;

In [3]:
import pandas as pd

Array Creation and Manipulation

In [8]:
# Q1.1: Create a 4x4 identity matrix using np.eye()

identity_matrix=np.eye(4,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [10]:
# Q1.2: Create an array of 8 zeros using np.zeros()
array=np.zeros(8)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0.]

In [11]:
# Q1.3: Create an array of 6 ones using np.ones()

ones=np.ones(6)
print(ones)

[1. 1. 1. 1. 1. 1.]

In [13]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
array=np.arange(0,15)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

In [14]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

evenly_spaced=np.linspace(0,100,8)
print(evenly_spaced)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]

Array Attributes and Information

In [4]:
np.random.seed(222)
data_values=np.array([
    np.arange(1,11),
    np.random.randint(1000,10000,10),
    np.random.randint(300,800,10),
    np.random.randint(1,40,10),
    np.random.randint(1,10,10)
])
# data=pd.DataFrame(data_values)
data1=data_values.T
print(data1)

[[   1 4206  710   18    5]
 [   2 6165  644   10    6]
 [   3 9165  420    9    5]
 [   4 2366  444   16    6]
 [   5 9301  576   15    6]
 [   6 1765  377   30    5]
 [   7 8420  795   30    9]
 [   8 2800  383   36    5]
 [   9 5084  335    8    9]
 [  10 7599  776   24    1]]

In [5]:
np.random.seed(222)
data_values=({
    "Customer_ID":np.arange(1,11),
    "Account_Balance":np.random.randint(1000,10000,10),
    "Credit_Score":np.random.randint(300,800,10),
    "Transaction_Count":np.random.randint(1,40,10),
    "Years_Active":np.random.randint(1,10,10)
})
data=pd.DataFrame(data_values)
print(data)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0            1             4206           710                 18             5
1            2             6165           644                 10             6
2            3             9165           420                  9             5
3            4             2366           444                 16             6
4            5             9301           576                 15             6
5            6             1765           377                 30             5
6            7             8420           795                 30             9
7            8             2800           383                 36             5
8            9             5084           335                  8             9
9           10             7599           776                 24             1

In [57]:
# Q2.1: What is the shape of the banking_data array?
shape_array=np.shape(data1)
print(shape_array)

(10, 5)

In [ ]:
# Q2.2: What is the data type of the banking_data array?

type=data1.dtype
print(type)

TypeError: 'numpy.dtypes.Int64DType' object is not callable

In [68]:
# Q2.3: What is the size (total number of elements) of the banking_data array?

print(data1.size)

50

In [71]:
# Q2.4: What is the number of dimensions of the banking_data array?
dime=data1.ndim
print(dime)

2

In [75]:
# Q2.5: What is the memory size of the banking_data array in bytes?

size=data1.nbytes
print(size)

400

 Indexing and Slicing

In [76]:
# Q3.1: Extract the first row of banking_data

data1[0]

array([   1, 4206,  710,   18,    5])

In [82]:
# Q3.2: Extract the last row of banking_data

data1[-1]

array([  10, 7599,  776,   24,    1])

In [88]:
# Q3.3: Extract the Account_Balance column (column index 1)

data1[:,1]

array([4206, 6165, 9165, 2366, 9301, 1765, 8420, 2800, 5084, 7599])

In [90]:
# Q3.4: Extract the first 4 rows and first 3 columns

data1[0:4,0:3]

array([[   1, 4206,  710],
       [   2, 6165,  644],
       [   3, 9165,  420],
       [   4, 2366,  444]])

In [8]:
# Q3.5: Extract rows 3 to 7 (inclusive)
data1[3:8,:]

array([[   4, 2366,  444,   16,    6],
       [   5, 9301,  576,   15,    6],
       [   6, 1765,  377,   30,    5],
       [   7, 8420,  795,   30,    9],
       [   8, 2800,  383,   36,    5]])

Question 4: Mathematical Operations

In [16]:
# Q4.1: Calculate the sum of all account balances

sum_b=np.sum(data["Account_Balance"])
print(sum_b)

56871

In [21]:
sum_b=np.sum(data1[:,1])
print(sum_b)

56871

In [17]:
# Q4.2: Calculate the mean account balance
mean_b=np.mean(data["Account_Balance"])
print(mean_b)

5687.1

In [ ]:
mean_b=np.mean(data1[:,1])
print(mean_b)
#######using arrays

5687.1

In [18]:
# Q4.3: Calculate the standard deviation of account balances

dev=np.std(data["Account_Balance"])
print(dev)

2716.8706428536493

In [ ]:
# Q4.4: Calculate the variance of account balances
var=np.var(data["Account_Balance"])
print(var)
#### variance is square of std

7381386.090000001

In [23]:
# Q4.5: Calculate the median account balance

med=np.median(data["Account_Balance"])
print(med)

5624.5

Question 5: Statistical Functions

In [24]:
# Q5.1: Find the minimum and maximum account balances

maxx=np.max(data["Account_Balance"])
minn=np.min(data["Account_Balance"])
print("maximum is",maxx)
print("minimumn is",minn)

maximum is 9301
minimumn is 1765

In [25]:
# Q5.2: Find the minimum and maximum credit scores
maxx=np.max(data["Credit_Score"])
minn=np.min(data["Credit_Score"])
print("maximum is",maxx)
print("minimumn is",minn)

maximum is 795
minimumn is 335

In [29]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)

perc=np.quantile(data["Account_Balance"],[0.25,0.5,0.75])
print(perc)

[3151.5  5624.5  8214.75]

In [33]:
# Q5.4: Calculate the correlation between account balance and credit score
cred=np.corrcoef(data["Account_Balance"],data["Credit_Score"])
print(cred)

[[1.        0.4840889]
 [0.4840889 1.       ]]

In [34]:
# Q5.5: Calculate the covariance between account balance and credit score

cred=np.cov(data["Account_Balance"],data["Credit_Score"])
print(cred)

[[8201540.1         243755.88888889]
 [ 243755.88888889   30914.66666667]]

Question 6: Array Reshaping and Manipulation

In [36]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns

shape=np.reshape(data1,(5,10))
print(shape)

[[   1 4206  710   18    5    2 6165  644   10    6]
 [   3 9165  420    9    5    4 2366  444   16    6]
 [   5 9301  576   15    6    6 1765  377   30    5]
 [   7 8420  795   30    9    8 2800  383   36    5]
 [   9 5084  335    8    9   10 7599  776   24    1]]

In [38]:
# Q6.2: Flatten the banking_data to a 1D array
shape=data1.flatten()
print(shape)

[   1 4206  710   18    5    2 6165  644   10    6    3 9165  420    9
    5    4 2366  444   16    6    5 9301  576   15    6    6 1765  377
   30    5    7 8420  795   30    9    8 2800  383   36    5    9 5084
  335    8    9   10 7599  776   24    1]

In [39]:
# Q6.3: Transpose the banking_data

add=data1.T
print(add)

[[   1    2    3    4    5    6    7    8    9   10]
 [4206 6165 9165 2366 9301 1765 8420 2800 5084 7599]
 [ 710  644  420  444  576  377  795  383  335  776]
 [  18   10    9   16   15   30   30   36    8   24]
 [   5    6    5    6    6    5    9    5    9    1]]

In [40]:
data1

array([[   1, 4206,  710,   18,    5],
       [   2, 6165,  644,   10,    6],
       [   3, 9165,  420,    9,    5],
       [   4, 2366,  444,   16,    6],
       [   5, 9301,  576,   15,    6],
       [   6, 1765,  377,   30,    5],
       [   7, 8420,  795,   30,    9],
       [   8, 2800,  383,   36,    5],
       [   9, 5084,  335,    8,    9],
       [  10, 7599,  776,   24,    1]])

In [48]:
# Q6.4: Split the banking_data into 2 equal parts vertically

spl,spl2=np.split(data1,2)
print("first part",spl)
print("last part",spl2)

first part [[   1 4206  710   18    5]
 [   2 6165  644   10    6]
 [   3 9165  420    9    5]
 [   4 2366  444   16    6]
 [   5 9301  576   15    6]]
last part [[   6 1765  377   30    5]
 [   7 8420  795   30    9]
 [   8 2800  383   36    5]
 [   9 5084  335    8    9]
 [  10 7599  776   24    1]]

In [52]:
# Q6.5: Split the banking_data into 2 equal parts horizontally

spl, spl2 = np.split(data1, 2, axis=0)
print("first part", spl)
print("last part", spl2)

first part [[   1 4206  710   18    5]
 [   2 6165  644   10    6]
 [   3 9165  420    9    5]
 [   4 2366  444   16    6]
 [   5 9301  576   15    6]]
last part [[   6 1765  377   30    5]
 [   7 8420  795   30    9]
 [   8 2800  383   36    5]
 [   9 5084  335    8    9]
 [  10 7599  776   24    1]]

Question 7: Logical Operations and Filtering

In [54]:
# Q7.1: Find customers with account balance greater than $100,000
high=data[data["Account_Balance"]>7000]
print("the greater than 7000 is:",high)

the greater than 7000 is:    Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
2            3             9165           420                  9             5
4            5             9301           576                 15             6
6            7             8420           795                 30             9
9           10             7599           776                 24             1

In [58]:
# Q7.2: Find customers with credit score greater than 800
cred=data[data["Credit_Score"]>500]
print("the scores are:",cred)

the scores are:    Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0            1             4206           710                 18             5
1            2             6165           644                 10             6
4            5             9301           576                 15             6
6            7             8420           795                 30             9
9           10             7599           776                 24             1

In [60]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750

val=data[(data["Transaction_Count"]>5) & (data["Credit_Score"]>550)]
print(val)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0            1             4206           710                 18             5
1            2             6165           644                 10             6
4            5             9301           576                 15             6
6            7             8420           795                 30             9
9           10             7599           776                 24             1

In [63]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
numb_customer=data[(data["Account_Balance"] >4000)&(data["Account_Balance"]<8000)]
print(numb_customer.shape[0])

4

In [68]:
# Q7.5: Find the index of the customer with the highest credit score
index=data["Credit_Score"].idxmax()
print(index)

6

Question 8: Sorting and Searching

In [69]:
# Q8.1: Sort the banking_data by account balance (ascending)

sorted=data.sort_values(by="Account_Balance",ascending=True)
print(sorted)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
5            6             1765           377                 30             5
3            4             2366           444                 16             6
7            8             2800           383                 36             5
0            1             4206           710                 18             5
8            9             5084           335                  8             9
1            2             6165           644                 10             6
9           10             7599           776                 24             1
6            7             8420           795                 30             9
2            3             9165           420                  9             5
4            5             9301           576                 15             6

In [70]:
# Q8.2: Sort the banking_data by credit score (descending)
sorted=data.sort_values(by="Credit_Score",ascending=False)
print(sorted)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
6            7             8420           795                 30             9
9           10             7599           776                 24             1
0            1             4206           710                 18             5
1            2             6165           644                 10             6
4            5             9301           576                 15             6
3            4             2366           444                 16             6
2            3             9165           420                  9             5
7            8             2800           383                 36             5
5            6             1765           377                 30             5
8            9             5084           335                  8             9

In [72]:
# Q8.3: Find the indices that would sort the array by years active
sorted=data.sort_values(by="Years_Active",ascending=True).index
print(sorted)

Index([9, 0, 2, 5, 7, 1, 3, 4, 6, 8], dtype='int64')

In [75]:
# Q8.4: Find the customer with the second highest account balance
high=data.sort_values(by="Account_Balance",ascending=False).iloc[1]
print(high)

Customer_ID             3
Account_Balance      9165
Credit_Score          420
Transaction_Count       9
Years_Active            5
Name: 2, dtype: int64

In [ ]:
# Q8.5: Find the customer with the lowest transaction count

low=data.sort_values(by="Transaction_Count",ascending=True).iloc[0]
print(low)

Customer_ID             9
Account_Balance      5084
Credit_Score          335
Transaction_Count       8
Years_Active            9
Name: 8, dtype: int64

Question 9: Mathematical Functions

In [78]:
# Q9.1: Calculate the absolute values of all elements

abso=np.abs(data1)
abso

array([[   1, 4206,  710,   18,    5],
       [   2, 6165,  644,   10,    6],
       [   3, 9165,  420,    9,    5],
       [   4, 2366,  444,   16,    6],
       [   5, 9301,  576,   15,    6],
       [   6, 1765,  377,   30,    5],
       [   7, 8420,  795,   30,    9],
       [   8, 2800,  383,   36,    5],
       [   9, 5084,  335,    8,    9],
       [  10, 7599,  776,   24,    1]])

In [82]:
# Q9.2: Calculate the square root of all account balances

sqrtoo=np.sqrt(data["Account_Balance"])
sqrtoo

0    64.853681
1    78.517514
2    95.734006
3    48.641546
4    96.441692
5    42.011903
6    91.760558
7    52.915026
8    71.302174
9    87.172243
Name: Account_Balance, dtype: float64

In [83]:
# Q9.3: Calculate the square of all credit scores
sqroo=np.square(data["Credit_Score"])
sqroo

0    504100
1    414736
2    176400
3    197136
4    331776
5    142129
6    632025
7    146689
8    112225
9    602176
Name: Credit_Score, dtype: int64

In [84]:
# Q9.4: Calculate the exponential of all transaction counts
expo=np.exp(data["Transaction_Count"])
expo

0    6.565997e+07
1    2.202647e+04
2    8.103084e+03
3    8.886111e+06
4    3.269017e+06
5    1.068647e+13
6    1.068647e+13
7    4.311232e+15
8    2.980958e+03
9    2.648912e+10
Name: Transaction_Count, dtype: float64

In [85]:
# Q9.5: Calculate the natural logarithm of all account balances
logo=np.log(data["Account_Balance"])
logo

0    8.344267
1    8.726643
2    9.123147
3    7.768956
4    9.137877
5    7.475906
6    9.038365
7    7.937375
8    8.533854
9    8.935772
Name: Account_Balance, dtype: float64

In [86]:
log_all=data.select_dtypes(include=[int,float]).apply(np.log)
log_all

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0     0.000000         8.344267      6.565265           2.890372      1.609438
1     0.693147         8.726643      6.467699           2.302585      1.791759
2     1.098612         9.123147      6.040255           2.197225      1.609438
3     1.386294         7.768956      6.095825           2.772589      1.791759
4     1.609438         9.137877      6.356108           2.708050      1.791759
5     1.791759         7.475906      5.932245           3.401197      1.609438
6     1.945910         9.038365      6.678342           3.401197      2.197225
7     2.079442         7.937375      5.948035           3.583519      1.609438
8     2.197225         8.533854      5.814131           2.079442      2.197225
9     2.302585         8.935772      6.654153           3.178054      0.000000

Question 10: Advanced Operations

In [87]:
# Q10.1: Calculate the cumulative sum of account balances
cum=np.cumsum(data['Account_Balance'])
cum

0     4206
1    10371
2    19536
3    21902
4    31203
5    32968
6    41388
7    44188
8    49272
9    56871
Name: Account_Balance, dtype: int64

In [88]:
# Q10.2: Calculate the cumulative product of transaction counts

cum=np.cumprod(data["Transaction_Count"])
cum

0               18
1              180
2             1620
3            25920
4           388800
5         11664000
6        349920000
7      12597120000
8     100776960000
9    2418647040000
Name: Transaction_Count, dtype: int64

In [89]:
# Q10.3: Calculate the difference between consecutive account balances

diff=np.diff(data["Account_Balance"])
diff

array([ 1959,  3000, -6799,  6935, -7536,  6655, -5620,  2284,  2515])

In [90]:
# Q10.4: Calculate the gradient of account balances
gra=np.gradient(data["Account_Balance"])
gra

array([ 1959. ,  2479.5, -1899.5,    68. ,  -300.5,  -440.5,   517.5,
       -1668. ,  2399.5,  2515. ])

In [91]:
# Q10.5: Calculate the histogram of account balances with 5 bins
hist,bins=np.histogram(data["Account_Balance"],bins=5)
print("hist:",hist)
print("bin:",bins)

hist: [3 1 2 1 3]
bin: [1765.  3272.2 4779.4 6286.6 7793.8 9301. ]

Question 11: Random Numbers and Simulation

In [ ]:
# Q11.1: Generate 6 random integers between 1 and 1000

np.random.randint(1,1000,6)

array([222, 734, 517, 673, 849, 306])

In [93]:
# Q11.2: Generate 6 random floats between 0 and 1

np.random.rand(6)

array([0.58561187, 0.09678507, 0.02293824, 0.89247092, 0.47042902,
       0.22573503])

In [94]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)

np.random.seed(255)
num=np.random.normal(loc=700,scale=100,size=6)
num

array([548.6588138 , 680.29390806, 627.58138282, 783.4898056 ,
       582.5734265 , 658.67583188])

In [95]:
# Q11.4: Shuffle the banking_data rows randomly

shuffled_array = np.random.permutation(data1)
print(shuffled_array)

[[   6 1765  377   30    5]
 [   7 8420  795   30    9]
 [   4 2366  444   16    6]
 [   3 9165  420    9    5]
 [   1 4206  710   18    5]
 [   9 5084  335    8    9]
 [  10 7599  776   24    1]
 [   5 9301  576   15    6]
 [   2 6165  644   10    6]
 [   8 2800  383   36    5]]

In [96]:
# Q11.5: Set random seed to 123 and generate 4 random numbers

np.random.seed(123)
num=np.random.randint(1,10,6)
num

array([3, 3, 7, 2, 4, 7])

Question 12: Linear Algebra Operations

In [98]:
# Q12.1: Calculate the dot product of account balance and credit score columns
dotu=np.dot(data["Account_Balance"],data["Credit_Score"])
dotu

np.int64(33245369)

In [104]:
# Q12.2: Calculate the cross product of first two rows
row=np.cross(data1[0,1:4],data1[1,1:4])
print(row)

[   -4492    68910 -1668486]

In [105]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
mag = np.linalg.norm(data["Account_Balance"])
print(mag)

19931.004114193544

In [107]:
# Q12.4: Create a 3x3 matrix and calculate its determinant

data2=np.random.randint(1,10,(3,3))
deter=np.linalg.det(data2)
deter

np.float64(-55.99999999999997)

In [110]:
# Q12.5: Calculate the inverse of the 3x3 matrix
dat=np.random.randint(1,10,(3,3))
inv=np.linalg.inv(dat)
inv

array([[ 2.33333333, -1.        , -1.33333333],
       [-0.33333333, -0.        ,  0.33333333],
       [-1.28571429,  0.71428571,  0.71428571]])

Question 13: String Operations

In [114]:
# Q13.1: Convert all customer IDs to strings

id=data["Customer_ID"].astype(str)
id

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Customer_ID, dtype: object

In [115]:
# Q13.2: Check if any customer ID contains '100'
num=data["Customer_ID"].astype(str).str.contains("100")
num

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Customer_ID, dtype: bool

In [116]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
num=data["Customer_ID"].astype(str).str.upper()
num

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Customer_ID, dtype: object

In [118]:
# Q13.4: Count the length of each customer ID string
num=data["Customer_ID"].astype(str)
leng=num.str.len()
leng

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    2
Name: Customer_ID, dtype: int64

In [120]:
# Q13.5: Replace '100' with 'CUST' in customer IDs
num=data["Customer_ID"].astype(str).str.replace("100","cust")
num

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Customer_ID, dtype: object

Question 14: Date and Time Operations

In [121]:
# Q14.1: Convert years active to months
num=data["Years_Active"]*12
num

0     60
1     72
2     60
3     72
4     72
5     60
6    108
7     60
8    108
9     12
Name: Years_Active, dtype: int64

In [124]:
# Q14.2: Calculate the average years active

num=np.mean(data["Years_Active"])
num

np.float64(5.7)

In [125]:
# Q14.3: Find customers who have been active for more than 5 years

num=data[data["Years_Active"]>5]
num

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
1            2             6165           644                 10             6
3            4             2366           444                 16             6
4            5             9301           576                 15             6
6            7             8420           795                 30             9
8            9             5084           335                  8             9

In [128]:
# Q14.4: Calculate the total time all customers have been active (in years)

num=np.sum(data["Years_Active"])
num

np.int64(57)

In [135]:
# Q14.5: Find the customer with the shortest time active

# Find the customer(s) with the minimum years active
min_active_customer = data[data["Years_Active"] == data["Years_Active"].min()]
print(min_active_customer)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
9           10             7599           776                 24             1

Question 16: Array Concatenation and Stacking

In [ ]:
# Q16.1: Concatenate two arrays horizontally using np.hstack()

con = np.hstack((data1, data1))
print(con)

[[   1 4206  710   18    5    1 4206  710   18    5]
 [   2 6165  644   10    6    2 6165  644   10    6]
 [   3 9165  420    9    5    3 9165  420    9    5]
 [   4 2366  444   16    6    4 2366  444   16    6]
 [   5 9301  576   15    6    5 9301  576   15    6]
 [   6 1765  377   30    5    6 1765  377   30    5]
 [   7 8420  795   30    9    7 8420  795   30    9]
 [   8 2800  383   36    5    8 2800  383   36    5]
 [   9 5084  335    8    9    9 5084  335    8    9]
 [  10 7599  776   24    1   10 7599  776   24    1]]

In [9]:
# Q16.2: Concatenate two arrays vertically using np.vstack()

con = np.vstack((data1, data1))
print(con)

[[   1 4206  710   18    5]
 [   2 6165  644   10    6]
 [   3 9165  420    9    5]
 [   4 2366  444   16    6]
 [   5 9301  576   15    6]
 [   6 1765  377   30    5]
 [   7 8420  795   30    9]
 [   8 2800  383   36    5]
 [   9 5084  335    8    9]
 [  10 7599  776   24    1]
 [   1 4206  710   18    5]
 [   2 6165  644   10    6]
 [   3 9165  420    9    5]
 [   4 2366  444   16    6]
 [   5 9301  576   15    6]
 [   6 1765  377   30    5]
 [   7 8420  795   30    9]
 [   8 2800  383   36    5]
 [   9 5084  335    8    9]
 [  10 7599  776   24    1]]

In [21]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()

cot = np.concatenate((data1,data1),axis=0)
print(cot)

[[   1 4206  710   18    5]
 [   2 6165  644   10    6]
 [   3 9165  420    9    5]
 [   4 2366  444   16    6]
 [   5 9301  576   15    6]
 [   6 1765  377   30    5]
 [   7 8420  795   30    9]
 [   8 2800  383   36    5]
 [   9 5084  335    8    9]
 [  10 7599  776   24    1]
 [   1 4206  710   18    5]
 [   2 6165  644   10    6]
 [   3 9165  420    9    5]
 [   4 2366  444   16    6]
 [   5 9301  576   15    6]
 [   6 1765  377   30    5]
 [   7 8420  795   30    9]
 [   8 2800  383   36    5]
 [   9 5084  335    8    9]
 [  10 7599  776   24    1]]

In [24]:
# Q16.4: Stack arrays depth-wise using np.dstack()

cot = np.dstack((data1,data1))
print(cot)

[[[   1    1]
  [4206 4206]
  [ 710  710]
  [  18   18]
  [   5    5]]

 [[   2    2]
  [6165 6165]
  [ 644  644]
  [  10   10]
  [   6    6]]

 [[   3    3]
  [9165 9165]
  [ 420  420]
  [   9    9]
  [   5    5]]

 [[   4    4]
  [2366 2366]
  [ 444  444]
  [  16   16]
  [   6    6]]

 [[   5    5]
  [9301 9301]
  [ 576  576]
  [  15   15]
  [   6    6]]

 [[   6    6]
  [1765 1765]
  [ 377  377]
  [  30   30]
  [   5    5]]

 [[   7    7]
  [8420 8420]
  [ 795  795]
  [  30   30]
  [   9    9]]

 [[   8    8]
  [2800 2800]
  [ 383  383]
  [  36   36]
  [   5    5]]

 [[   9    9]
  [5084 5084]
  [ 335  335]
  [   8    8]
  [   9    9]]

 [[  10   10]
  [7599 7599]
  [ 776  776]
  [  24   24]
  [   1    1]]]

In [26]:
# Q16.5: Create a column stack using np.column_stack()

cot = np.column_stack((data1,data1))
print(cot)

[[   1 4206  710   18    5    1 4206  710   18    5]
 [   2 6165  644   10    6    2 6165  644   10    6]
 [   3 9165  420    9    5    3 9165  420    9    5]
 [   4 2366  444   16    6    4 2366  444   16    6]
 [   5 9301  576   15    6    5 9301  576   15    6]
 [   6 1765  377   30    5    6 1765  377   30    5]
 [   7 8420  795   30    9    7 8420  795   30    9]
 [   8 2800  383   36    5    8 2800  383   36    5]
 [   9 5084  335    8    9    9 5084  335    8    9]
 [  10 7599  776   24    1   10 7599  776   24    1]]

Question 17: Array Splitting Operations

In [28]:
# Q17.1: Split an array into 3 equal parts using np.split()

data=np.split(data1,2)
data

[array([[   1, 4206,  710,   18,    5],
        [   2, 6165,  644,   10,    6],
        [   3, 9165,  420,    9,    5],
        [   4, 2366,  444,   16,    6],
        [   5, 9301,  576,   15,    6]]),
 array([[   6, 1765,  377,   30,    5],
        [   7, 8420,  795,   30,    9],
        [   8, 2800,  383,   36,    5],
        [   9, 5084,  335,    8,    9],
        [  10, 7599,  776,   24,    1]])]

In [29]:
# Q17.2: Split an array at specific indices using np.split()
dot=np.split(data1,[3,6])
dot

[array([[   1, 4206,  710,   18,    5],
        [   2, 6165,  644,   10,    6],
        [   3, 9165,  420,    9,    5]]),
 array([[   4, 2366,  444,   16,    6],
        [   5, 9301,  576,   15,    6],
        [   6, 1765,  377,   30,    5]]),
 array([[   7, 8420,  795,   30,    9],
        [   8, 2800,  383,   36,    5],
        [   9, 5084,  335,    8,    9],
        [  10, 7599,  776,   24,    1]])]

In [33]:
# Q17.3: Split an array horizontally using np.hsplit()

dot=np.hsplit(data1,5)
dot

[array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 array([[4206],
        [6165],
        [9165],
        [2366],
        [9301],
        [1765],
        [8420],
        [2800],
        [5084],
        [7599]]),
 array([[710],
        [644],
        [420],
        [444],
        [576],
        [377],
        [795],
        [383],
        [335],
        [776]]),
 array([[18],
        [10],
        [ 9],
        [16],
        [15],
        [30],
        [30],
        [36],
        [ 8],
        [24]]),
 array([[5],
        [6],
        [5],
        [6],
        [6],
        [5],
        [9],
        [5],
        [9],
        [1]])]

In [35]:
# Q17.4: Split an array vertically using np.vsplit()
split=np.vsplit(data1,2)
split

[array([[   1, 4206,  710,   18,    5],
        [   2, 6165,  644,   10,    6],
        [   3, 9165,  420,    9,    5],
        [   4, 2366,  444,   16,    6],
        [   5, 9301,  576,   15,    6]]),
 array([[   6, 1765,  377,   30,    5],
        [   7, 8420,  795,   30,    9],
        [   8, 2800,  383,   36,    5],
        [   9, 5084,  335,    8,    9],
        [  10, 7599,  776,   24,    1]])]

In [36]:
# Q17.5: Split an array into equal chunks using np.array_split()
split=np.array_split(data1,2)
split

[array([[   1, 4206,  710,   18,    5],
        [   2, 6165,  644,   10,    6],
        [   3, 9165,  420,    9,    5],
        [   4, 2366,  444,   16,    6],
        [   5, 9301,  576,   15,    6]]),
 array([[   6, 1765,  377,   30,    5],
        [   7, 8420,  795,   30,    9],
        [   8, 2800,  383,   36,    5],
        [   9, 5084,  335,    8,    9],
        [  10, 7599,  776,   24,    1]])]



Question 18: Array Repetition and Tiling

In [46]:
# Q18.1: Repeat each element of an array 3 times using np.repeat()

rep=np.repeat(data1,3)
rep

array([   1,    1,    1, 4206, 4206, 4206,  710,  710,  710,   18,   18,
         18,    5,    5,    5,    2,    2,    2, 6165, 6165, 6165,  644,
        644,  644,   10,   10,   10,    6,    6,    6,    3,    3,    3,
       9165, 9165, 9165,  420,  420,  420,    9,    9,    9,    5,    5,
          5,    4,    4,    4, 2366, 2366, 2366,  444,  444,  444,   16,
         16,   16,    6,    6,    6,    5,    5,    5, 9301, 9301, 9301,
        576,  576,  576,   15,   15,   15,    6,    6,    6,    6,    6,
          6, 1765, 1765, 1765,  377,  377,  377,   30,   30,   30,    5,
          5,    5,    7,    7,    7, 8420, 8420, 8420,  795,  795,  795,
         30,   30,   30,    9,    9,    9,    8,    8,    8, 2800, 2800,
       2800,  383,  383,  383,   36,   36,   36,    5,    5,    5,    9,
          9,    9, 5084, 5084, 5084,  335,  335,  335,    8,    8,    8,
          9,    9,    9,   10,   10,   10, 7599, 7599, 7599,  776,  776,
        776,   24,   24,   24,    1,    1,    1])

In [39]:
# Q18.2: Repeat an entire array 2 times using np.tile()

rep=np.tile(data1,2)
rep

array([[   1, 4206,  710,   18,    5,    1, 4206,  710,   18,    5],
       [   2, 6165,  644,   10,    6,    2, 6165,  644,   10,    6],
       [   3, 9165,  420,    9,    5,    3, 9165,  420,    9,    5],
       [   4, 2366,  444,   16,    6,    4, 2366,  444,   16,    6],
       [   5, 9301,  576,   15,    6,    5, 9301,  576,   15,    6],
       [   6, 1765,  377,   30,    5,    6, 1765,  377,   30,    5],
       [   7, 8420,  795,   30,    9,    7, 8420,  795,   30,    9],
       [   8, 2800,  383,   36,    5,    8, 2800,  383,   36,    5],
       [   9, 5084,  335,    8,    9,    9, 5084,  335,    8,    9],
       [  10, 7599,  776,   24,    1,   10, 7599,  776,   24,    1]])

In [40]:
# Q18.3: Repeat a 2D array using np.tile()

rep = np.tile(data1, (2,2))
rep

array([[   1, 4206,  710,   18,    5,    1, 4206,  710,   18,    5],
       [   2, 6165,  644,   10,    6,    2, 6165,  644,   10,    6],
       [   3, 9165,  420,    9,    5,    3, 9165,  420,    9,    5],
       [   4, 2366,  444,   16,    6,    4, 2366,  444,   16,    6],
       [   5, 9301,  576,   15,    6,    5, 9301,  576,   15,    6],
       [   6, 1765,  377,   30,    5,    6, 1765,  377,   30,    5],
       [   7, 8420,  795,   30,    9,    7, 8420,  795,   30,    9],
       [   8, 2800,  383,   36,    5,    8, 2800,  383,   36,    5],
       [   9, 5084,  335,    8,    9,    9, 5084,  335,    8,    9],
       [  10, 7599,  776,   24,    1,   10, 7599,  776,   24,    1],
       [   1, 4206,  710,   18,    5,    1, 4206,  710,   18,    5],
       [   2, 6165,  644,   10,    6,    2, 6165,  644,   10,    6],
       [   3, 9165,  420,    9,    5,    3, 9165,  420,    9,    5],
       [   4, 2366,  444,   16,    6,    4, 2366,  444,   16,    6],
       [   5, 9301,  576,   15,    6,    5, 9301,  576,   15,    6],
       [   6, 1765,  377,   30,    5,    6, 1765,  377,   30,    5],
       [   7, 8420,  795,   30,    9,    7, 8420,  795,   30,    9],
       [   8, 2800,  383,   36,    5,    8, 2800,  383,   36,    5],
       [   9, 5084,  335,    8,    9,    9, 5084,  335,    8,    9],
       [  10, 7599,  776,   24,    1,   10, 7599,  776,   24,    1]])

In [43]:
# Q18.4: Create a pattern using np.tile()

pat = np.tile([[4,0],[0,4]], (3,3))
pat

array([[4, 0, 4, 0, 4, 0],
       [0, 4, 0, 4, 0, 4],
       [4, 0, 4, 0, 4, 0],
       [0, 4, 0, 4, 0, 4],
       [4, 0, 4, 0, 4, 0],
       [0, 4, 0, 4, 0, 4]])

In [44]:
# Q18.5: Repeat elements with different counts using np.repeat()

rep = np.repeat(data1, 2)
rep

array([   1,    1, 4206, 4206,  710,  710,   18,   18,    5,    5,    2,
          2, 6165, 6165,  644,  644,   10,   10,    6,    6,    3,    3,
       9165, 9165,  420,  420,    9,    9,    5,    5,    4,    4, 2366,
       2366,  444,  444,   16,   16,    6,    6,    5,    5, 9301, 9301,
        576,  576,   15,   15,    6,    6,    6,    6, 1765, 1765,  377,
        377,   30,   30,    5,    5,    7,    7, 8420, 8420,  795,  795,
         30,   30,    9,    9,    8,    8, 2800, 2800,  383,  383,   36,
         36,    5,    5,    9,    9, 5084, 5084,  335,  335,    8,    8,
          9,    9,   10,   10, 7599, 7599,  776,  776,   24,   24,    1,
          1])

Question 19: Array Comparison and Logical Operations

In [48]:
# Q19.1: Compare two arrays for equality using np.array_equal()

data=np.array_equal(data1,data1)
data

True

In [51]:
# Q19.2: Check if arrays are close using np.allclose()

dot=np.allclose(data1,data1)
dot

True

In [ ]:
# Q19.3: Apply logical AND operation between arrays

In [ ]:
# Q19.4: Apply logical OR operation between arrays

In [ ]:
# Q19.5: Apply logical NOT operation to an array


Question 20: Array Set Operations

In [52]:
# Q20.1: Find unique elements in an array using np.unique()

data=np.unique(data1)
data

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   15,
         16,   18,   24,   30,   36,  335,  377,  383,  420,  444,  576,
        644,  710,  776,  795, 1765, 2366, 2800, 4206, 5084, 6165, 7599,
       8420, 9165, 9301])

In [53]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()

data=np.intersect1d(data1,data1)
data

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   15,
         16,   18,   24,   30,   36,  335,  377,  383,  420,  444,  576,
        644,  710,  776,  795, 1765, 2366, 2800, 4206, 5084, 6165, 7599,
       8420, 9165, 9301])

In [54]:
# Q20.3: Find the union of two arrays using np.union1d()
data=np.union1d(data1,data1)
data

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   15,
         16,   18,   24,   30,   36,  335,  377,  383,  420,  444,  576,
        644,  710,  776,  795, 1765, 2366, 2800, 4206, 5084, 6165, 7599,
       8420, 9165, 9301])

In [55]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
data=np.setdiff1d(data1,data1)
data

array([], dtype=int64)

In [56]:
# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()

data=np.setxor1d(data1,data1)
data

array([], dtype=int64)